---
name: prometheus

instance_groups:
  - name: alertmanager
    azs:
      - nova				#
    instances: 1
    vm_type: default			#
    persistent_disk: 1_024		#
    stemcell: default
    networks:
      - name: test			#
    jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            mesh:
              password: ((alertmanager_mesh_password))			#這邊對應以下變數
            route:
              receiver: default
            receivers:
              - name: default
            test_alert:
              daily: true

  - name: prometheus2
    azs:
      - nova				#
    instances: 1
    vm_type: default			#
    persistent_disk: 10_24
    stemcell: default			#
    networks:
      - name: test			#
    jobs:
      - name: prometheus2
        release: prometheus
        properties:
          prometheus:
            rule_files:
              - /var/vcap/jobs/postgres_alerts/*.alerts.yml
              - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090
      - name: postgres_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus

  - name: database
    azs:
      - nova					#
    instances: 1
    vm_type: default				#
    persistent_disk: 10_24			#
    stemcell: default
    networks:
      - name: test				#
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases:
            port: 5432
            databases:
              - name: grafana
                citext: true
            roles:
              - name: grafana
                password: ((postgres_grafana_password))
      - name: postgres_exporter
        release: prometheus
        properties:
          postgres_exporter:				#這邊的port號要打開,面板上面才看的到(5432)
            datasource_name: postgresql://grafana:((postgres_grafana_password))@127.0.0.1:5432/?sslmode=disable

  - name: grafana
    azs:
      - nova						#
    instances: 1
    vm_type: default					#
    persistent_disk: 1_024				#
    stemcell: default
    networks:
      - name: test					#
    jobs:
      - name: grafana
        release: prometheus
        properties:
          grafana:
            database:
              type: postgres
              port: 5432
              name: grafana
              user: grafana
              password: ((postgres_grafana_password))		#
            session:
              provider: postgres
              provider_port: 5432
              provider_name: grafana
              provider_user: grafana
              provider_password: ((postgres_grafana_password))
            security:
              admin_user: admin
              admin_password: ((grafana_password))
              secret_key: ((grafana_secret_key))
            dashboards:
            prometheus:
              dashboard_folders:
                - name: Grafana
                  files:
                    - /var/vcap/jobs/grafana_dashboards/*.json
                - name: PostgreSQL
                  files:
                    - /var/vcap/jobs/postgres_dashboards/*.json
                - name: Prometheus
                  files:
                    - /var/vcap/jobs/prometheus_dashboards/*.json
      - name: grafana_dashboards
        release: prometheus
      - name: postgres_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus

  - name: nginx
    azs:
      - nova					#
    instances: 1
    vm_type: default				#
    stemcell: default				#
    networks:
      - name: test				#
    jobs:
      - name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              auth_users:
                - name: admin
                  password: ((alertmanager_password))				#
            prometheus:
              auth_users:
                - name: admin
                  password: ((prometheus_password))				#

variables:					###########這邊會自動生成密碼(deployment-var.yml)
  - name: alertmanager_password
    type: password
  - name: alertmanager_mesh_password
    type: password
  - name: prometheus_password
    type: password
  - name: postgres_grafana_password
    type: password
  - name: grafana_password
    type: password
  - name: grafana_secret_key
    type: password

update:						#更新設定
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

releases:				#在這邊設定,可以直接幫你下載要的版本
- name: postgres
  version: "28"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=28
  sha1: c1fcec62cb9d2e95e3b191e3c91d238e2b9d23fa
- name: prometheus
  version: 22.0.0
  url: https://github.com/bosh-prometheus/prometheus-boshrelease/releases/download/v22.0.0/prometheus-22.0.0.tgz
  sha1: b2c97721e1f8db7ffce2f849e02afe62e3005de7
